# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0021_auto_20170329_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sound', models.CharField(max_length=40)),
            ],
        ),
    ]
